"""The committed figures are valid, in bounds, and actually referenced.

There is no SVG rasteriser on the development VM, so the figures in docs/img/
are validated structurally instead: well-formed XML, a viewBox, an opaque
background rect (an SVG that relies on the default transparent background
becomes unreadable on GitHub's dark theme), and no ink outside the canvas ---
which is what catches a label that has grown past the edge of the card.

They are regenerated by `python3 docs/tools/make_figures.py`.
"""

import os
import re
import sys
import unittest

from pathlib import Path

from ttcheck import REPO, read

TOOLS = os.path.join(REPO, "docs", "tools")
IMG = os.path.join(REPO, "docs", "img")
if TOOLS not in sys.path:
    sys.path.insert(0, TOOLS)

import check_svg  # noqa: E402

# Tiny Tapeout's datasheet build limits images under docs/ to 512 kB each and
# 1 MB in total; staying inside that keeps the docs workflow green.
MAX_ONE = 512 * 1024
MAX_TOTAL = 1024 * 1024


def figures():
    return sorted(f for f in os.listdir(IMG) if f.endswith(".svg"))


class Figures(unittest.TestCase):
    def test_there_are_figures(self):
        self.assertTrue(figures(), "docs/img/ has no SVGs")

    def test_each_figure_is_structurally_sound(self):
        for name in figures():
            problems, kinds = check_svg.check(os.path.join(IMG, name))
            self.assertEqual(problems, [], f"{name}: {problems}")

    def test_each_figure_is_within_the_datasheet_size_limit(self):
        total = 0
        for name in figures():
            size = os.path.getsize(os.path.join(IMG, name))
            total += size
            self.assertLess(size, MAX_ONE, f"{name} is {size/1024:.0f} kB")
        self.assertLess(total, MAX_TOTAL,
                        f"docs/img totals {total/1024:.0f} kB")

    def test_every_figure_is_referenced_by_the_documentation(self):
        prose = "".join(
            read(Path(REPO) / f)
            for f in ("README.md", "docs/DESIGN.md", "docs/info.md")
            if os.path.isfile(os.path.join(REPO, f))
        )
        for name in figures():
            self.assertIn(name, prose,
                          f"docs/img/{name} is committed but nothing links to it")

    def test_every_referenced_image_exists(self):
        for f in ("README.md", "docs/DESIGN.md", "docs/info.md"):
            path = os.path.join(REPO, f)
            if not os.path.isfile(path):
                continue
            for src in re.findall(r"!\[[^\]]*\]\(([^)]+)\)", read(Path(path))):
                # ../../workflows/<name>/badge.svg is GitHub's relative badge
                # URL, not a file in the repository
                if src.startswith(("http", "../")):
                    continue
                self.assertTrue(
                    os.path.isfile(os.path.join(REPO, src.split("#")[0])),
                    f"{f} embeds {src}, which does not exist",
                )

    def test_generator_and_checker_are_committed(self):
        # the figures must be reproducible from the data, not one-off artefacts
        for name in ("make_figures.py", "blockdiagram.py", "svgplot.py",
                     "check_svg.py"):
            self.assertTrue(os.path.isfile(os.path.join(TOOLS, name)),
                            f"docs/tools/{name} is missing")


if __name__ == "__main__":
    unittest.main()
