#!/usr/bin/env bash
# Report peak-to-peak swing, max/min, and toggle period for one or more nodes
# in an ngspice .raw file, without opening the xschem/gaw GUI.
#
# Usage:
#   check_swing.sh <raw-file> <node> [node ...]
#
# <raw-file> is looked up in $SIMDIR (default: ~/.xschem/simulations, xschem's
# default netlist_dir) unless an absolute/relative path is given.
#
# Period is measured as the time between two rising crossings of 0.9V (mid
# rail for this 1.8V design), skipping the first crossing to avoid startup
# transients. If a node never crosses 0.9V the period measurement will report
# "no measurement" - that itself is a useful signal that the node is stuck
# near a rail rather than toggling.
#
# Example:
#   xschem -n -x -q CDR_tb.sch
#   ngspice -b ~/.xschem/simulations/CDR_tb.spice
#   ./check_swing.sh CDR_tb.raw vin+ clk+ clk-

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <raw-file> <node> [node ...]" >&2
  exit 1
fi

SIMDIR="${SIMDIR:-$HOME/.xschem/simulations}"
RAW="$1"; shift
if [[ "$RAW" != /* && "$RAW" != ./* ]]; then
  RAW="$SIMDIR/$RAW"
fi
if [ ! -f "$RAW" ]; then
  echo "raw file not found: $RAW" >&2
  exit 1
fi

TMP="$(mktemp /tmp/check_swing.XXXXXX.spice)"
trap 'rm -f "$TMP"' EXIT

{
  echo "* auto-generated by check_swing.sh - do not edit by hand"
  echo ".control"
  echo "  load $RAW"
  for node in "$@"; do
    safe="$(echo "$node" | sed 's/+/p/g; s/-/n/g' | tr -c 'A-Za-z0-9_' '_')"
    echo "  meas tran ${safe}_pp  PP  v($node)"
    echo "  meas tran ${safe}_max MAX v($node)"
    echo "  meas tran ${safe}_min MIN v($node)"
    echo "  meas tran ${safe}_per TRIG v($node) VAL=0.9 RISE=2 TARG v($node) VAL=0.9 RISE=3"
  done
  echo ".endc"
  echo ".end"
} > "$TMP"

ngspice -b "$TMP" || true
# ngspice exits non-zero here even on a fully clean run (it flags "no .tran/.dc
# analysis was run" since we only `load` + `meas`), so don't let that read as
# failure - only "Error: measure ... failed!" text in the output above is a
# real problem.
exit 0
