#!/usr/bin/env python3
"""devices_from_netlist.py <netlist.spice> <subckt> [outfile.tcl]

Emit a Magic Tcl script that instantiates every primitive device of one
.subckt, with the parameters taken straight from the xschem LVS netlist.

This does NOT place or route anything sensibly -- it drops the devices in a
row so you can move them. The point is that W/L/nf/m come from the netlist
instead of being retyped by hand -- in particular Magic's gencell wants W
PER FINGER while SPICE gives total W, and the PDK's -spice import does that
division for you (sky130A.tcl::mos_convert).

sky130_fd_pr__res_high_po at arbitrary W has no gencell in the stock magic
PDK -- only the fixed-width variants 0p35, 0p69, 1p41, 2p85, 5p73 do, and
this design uses W=1 and W=0.5. tcl/res_high_po_gencell.tcl supplies the
missing generator; the emitted script sources it automatically.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def load_subckt(path, name):
    """Return the logical (continuation-joined) lines of one .subckt."""
    lines = []
    with open(path) as fh:
        for raw in fh:
            raw = raw.rstrip("\n")
            if not raw or raw.lstrip().startswith("*"):
                continue
            if raw.startswith("+") and lines:
                lines[-1] += " " + raw[1:].strip()
            else:
                lines.append(raw)

    want = re.compile(r"^\.subckt\s+%s\s" % re.escape(name), re.I)
    body, inside = [], False
    for line in lines:
        if inside:
            if line.lower().startswith(".ends"):
                break
            body.append(line)
        elif want.match(line):
            inside = True
    if not inside:
        sys.exit("no .subckt %s in %s" % (name, path))
    return body


# Only these reach the PDK's *_convert procs; anything else is netlist noise
# (ad/as/pd/ps/nrd/nrs/sa/sb/sd) that Magic does not model.
KEEP = ("w", "l", "nf", "m", "mult")


def parse_device(line):
    """('XM1 a b c d model W=16 nf=8 ...') -> (inst, model, {param: value})."""
    toks = line.split()
    if not toks or not toks[0].upper().startswith("X"):
        return None
    inst = toks[0]
    model = params_at = None
    for i, tok in enumerate(toks):
        if tok.startswith("sky130_fd_pr__"):
            model, params_at = tok, i + 1
            break
    if model is None:
        return None                      # a subcircuit call, not a device

    params = {}
    for tok in toks[params_at:]:
        if "=" not in tok:
            continue
        key, val = tok.split("=", 1)
        key = key.lower()
        if key in KEEP and "'" not in val:
            params[key] = val
    # SPICE 'mult' and 'm' mean the same thing to the gencell converters
    if "mult" in params:
        params.setdefault("m", params.pop("mult"))
    else:
        params.pop("mult", None)
    return inst, model, params


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    netlist, cell = sys.argv[1], sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else None

    devices = []
    for line in load_subckt(netlist, cell):
        parsed = parse_device(line)
        if parsed:
            devices.append(parsed)

    tcl = ["# generated by devices_from_netlist.py -- do not edit",
           "# %s : %s : %d devices" % (netlist, cell, len(devices)),
           "source %s" % os.path.join(HERE, "res_high_po_gencell.tcl"),
           "load %s" % cell,
           "snap internal",
           "box values 0 0 0 0"]

    x = 0
    for inst, model, params in devices:
        args = " ".join("%s %s" % (k, params[k]) for k in KEEP if k in params)
        tcl.append("box position %dum 0um" % x)
        tcl.append("if {[catch {magic::gencell sky130::%s %s -spice %s} err]} {"
                   % (model, inst, args))
        tcl.append('    puts stderr "FAILED $err  ;# %s %s"' % (inst, model))
        tcl.append("} else {")
        tcl.append('    puts stdout "placed %s  %s  %s"' % (inst, model, args))
        tcl.append("}")
        x += 25

    tcl.append("writeall force")   # device cells too, not just the parent
    tcl.append("quit -noprompt")
    text = "\n".join(tcl) + "\n"

    if out:
        with open(out, "w") as fh:
            fh.write(text)
        print("wrote %s : %d devices" % (out, len(devices)), file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
